# Generated by Django 5.0.4 on 2024-09-19 15:49

import users.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Author', models.DateTimeField(auto_now=True)),
                ('Blog', models.TextField()),
                ('image', models.ImageField(upload_to=users.utils.users_listings_path)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
