# Generated by Django 5.0.4 on 2024-09-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_listing_delete_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='Blog',
        ),
    ]
