# Generated by Django 5.0.4 on 2024-09-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_listing_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Title',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
