# Generated by Django 5.0.4 on 2024-09-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Author',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
