# Generated by Django 5.0.4 on 2024-09-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_blog_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Blog',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Title',
            new_name='title',
        ),
    ]
